---
run:
  build-tags:
    - btrfs_noversion
    - libdm_no_deferred_remove
  timeout: 5m

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - whitespace

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
