#!/bin/bash
set -e

bundle_test_integration() {
	TESTFLAGS="$TESTFLAGS -check.v"
	go_test_dir ./integration
}

# subshell so that we can export PATH without breaking other things
(
	make binary
	make install-binary
	export GO15VENDOREXPERIMENT=1
	bundle_test_integration
) 2>&1
