name: Close Pull Request

on:
  pull_request_target:
    types: [opened]
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: superbrothers/close-pull-request@ee879b9fb4a35e8dbd1b2fa63c9c135b68af4be1
      with:
        comment: "This repository has been migrated to https://github.com/containers/container-libs. Please open your PR there."
