#!/bin/bash

ACTION="${1}"
shift

case "${ACTION}" in
get)
    read DOCKER_REGISTRY
    echo "{\"ServerURL\":\"${DOCKER_REGISTRY}\",\"Username\":\"foo\",\"Secret\":\"bar\"}"
    exit 0
    ;;
*)
    echo "not implemented"
    exit 1
    ;;
esac