#!/bin/bash

case "${1}" in
    get)
        read REGISTRY
        if [[ "${REGISTRY}" = "registry-a.com" ]]; then
	        echo "{\"ServerURL\":\"${REGISTRY}\",\"Username\":\"foo\",\"Secret\":\"bar\"}"
	else
		echo "{}"
	fi
        exit 0
    ;;
    store)
        read UNUSED
        exit 0
    ;;
    list)
        read UNUSED
        echo "{\"registry-a.com\":\"foo\"}"
        exit 0
    ;;
    *)
        echo "not implemented"
        exit 1
    ;;
esac
