#!/bin/bash

case "${1}" in
    get)
        read REGISTRY
        echo "{\"ServerURL\":\"${REGISTRY}\",\"Username\":\"foo\",\"Secret\":\"bar\"}"
        exit 0
    ;;
    list)
        read UNUSED
        echo "{\"registry-a.com\":\"foo\"}"
        exit 0
    ;;
    *)
        echo "not implemented"
        exit 1
    ;;
esac